import React, { useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, Leaf, Sparkles, BookOpen, Presentation, X, ChevronRight, Sprout, Filter, Layers3 } from 'lucide-react';

const orderInfo = {
  Caryophyllales: 'Orden muy diverso dentro de las eudicotiledóneas. Reúne plantas con adaptaciones a ambientes secos o salinos; en esta presentación aparecen Amaranthaceae y Cactaceae.',
  Sapindales: 'Orden de árboles y arbustos de importancia económica. Muchas familias producen frutos, resinas, maderas o compuestos aromáticos.',
  Magnoliales: 'Orden de angiospermas magnólidas, con flores primitivas en varios aspectos, numerosas piezas florales y hojas generalmente aromáticas.',
  Apiales: 'Orden de eudicotiledóneas con familias de gran valor alimenticio, medicinal y ornamental. Incluye plantas herbáceas aromáticas y árboles o lianas.',
  Gentianales: 'Orden de eudicotiledóneas con muchas especies de látex, flores vistosas y usos medicinales u ornamentales.',
  Alismatales: 'Orden principalmente de monocotiledóneas acuáticas o herbáceas. Varias familias poseen inflorescencias muy especializadas.',
  Arecales: 'Orden de las palmeras. Se caracteriza por plantas con tronco tipo estípite, hojas grandes y frutos de importancia alimenticia y artesanal.',
  Asterales: 'Orden de plantas con inflorescencias muy especializadas. Asteraceae es una de las familias más reconocibles por sus capítulos florales.',
  Lamiales: 'Orden amplio de eudicotiledóneas. Incluye familias con flores vistosas, plantas aromáticas, ornamentales y especies maderables.',
  Boraginales: 'Orden asociado a plantas con inflorescencias escorpioides y hojas simples. Varias especies tienen valor medicinal, melífero u ornamental.',
  Brassicales: 'Orden caracterizado por familias con compuestos de defensa y especies alimenticias importantes. Incluye Brassicaceae y Caricaceae.',
  Poales: 'Orden de monocotiledóneas muy importante ecológica y económicamente. Incluye plantas herbáceas, epífitas, graminoides y especies de páramo.',
  Cucurbitales: 'Orden donde varias especies producen frutos carnosos de consumo humano. En esta lámina destaca Cucurbitaceae.',
  Ericales: 'Orden de eudicotiledóneas con arbustos y árboles de importancia ornamental, alimenticia y ecológica, especialmente en zonas altoandinas.',
  Malpighiales: 'Orden muy diverso de eudicotiledóneas tropicales. Incluye plantas con látex, lianas y familias de importancia económica.',
  Fabales: 'Orden donde destaca Fabaceae, familia fundamental por sus legumbres, su valor alimenticio y la fijación biológica de nitrógeno.',
  Geraniales: 'Orden con hierbas y subarbustos, muchas veces aromáticos u ornamentales, con flores vistosas.',
  Zingiberales: 'Orden de monocotiledóneas tropicales con hojas grandes, pseudotallos y brácteas vistosas. Incluye heliconias.',
  Asparagales: 'Orden de monocotiledóneas con gran diversidad de hierbas ornamentales, bulbos, rizomas y flores vistosas.',
  Laurales: 'Orden de magnólidas aromáticas, generalmente leñosas, con hojas simples y aceites esenciales.',
  Malvales: 'Orden con familias de valor económico por fibras, alimentos, madera y ornamentales. Malvaceae incluye cacao y algodón.',
  Rosales: 'Orden de eudicotiledóneas con familias productoras de frutos y especies con látex o estructuras reproductivas especializadas.',
  Myrtales: 'Orden con árboles y arbustos, varias familias con aceites esenciales, flores vistosas y frutos comestibles.'
};

const laminas = [
  {
    id: 'lamina-1', title: 'Lámina 1', source: 'ANGIOSPERMAS 1.pdf · desde página 20', accent: '#7c3aed',
    description: 'Nueve familias representativas organizadas por orden, rasgos botánicos, usos, especies y datos importantes.',
    families: [
      ['Amaranthaceae','Caryophyllales','🌾','#9f2d5f','amaranto, quinoa, espinaca y paico',['Hierbas, arbustos o trepadoras','Hojas simples, alternas u opuestas, sin estípulas','Brácteas florales escariosas','Inflorescencia paniculada','Flor bisexual o unisexual','Fruto utrículo seco o cápsula'],['alimenticio','colorante','forraje','medicinal','ornamental'],['Amaranthus · amaranto','Chenopodium quinoa · quinoa','Spinacia oleracea · espinaca','Cyathula ambrosioides · paico'],'Dato importante: la quinoa tiene alto valor nutricional y se menciona como ideal para dietas veganas; la espinaca aporta minerales y vitaminas, y el paico se asocia a usos gastrointestinales.'],
      ['Anacardiaceae','Sapindales','🥭','#c86b1e','mango, cajú, molle y ovo',['Árboles, arbustos o lianas','Presencia de exudado resinoso, a veces tóxico','El exudado puede volverse negro al oxidarse por taninos','Hojas alternas, simples o compuestas imparipinnadas','Flores casi siempre unisexuales','Fruto tipo drupa'],['alimenticio','comercial','especiería','madera','medicinal','ornamental'],['Mangifera indica · mango','Anacardium occidentale · cajú','Schinus molle · molle','Spondias purpurea · ovo'],'Dato importante: reúne especies frutales conocidas y plantas resinosas; por eso tiene valor alimenticio, comercial, medicinal y maderable.'],
      ['Annonaceae','Magnoliales','🍈','#4d7c39','guanábana y chirimoya',['Árboles, arbustos o lianas','Corteza fibrosa y desprendible en tiras largas','Hojas alternas, simples, enteras y aromáticas','Flores verdosas o amarillentas','Numerosos estambres arreglados en espiral','Fruto agregado de bayas o racimo de monocarpos'],['alimenticio','artesanal','construcción','madera','medicinal','ornamental'],['Annona muricata · guanábana','Annona cherimola · chirimoya'],'Dato importante: en Ecuador se registran más de cien especies y varias endémicas; sus frutos tropicales tienen gran valor alimenticio.'],
      ['Apiaceae','Apiales','☘️','#0f9f8f','apio y perejil',['Árboles, arbustos o hierbas con entrenudos huecos','Hojas alternas, raramente opuestas','Láminas disectas o divididas','Pecíolo envainado con vaina desarrollada','Inflorescencia en umbela simple o compuesta','Fruto tipo esquizocarpo'],['alimenticio','comercial','construcción','forraje','medicina'],['Apium graveolens · apio','Petroselinum crispum · perejil'],'Dato importante: se reconoce fácilmente por las umbelas; muchas especies son usadas como condimentos, hortalizas o plantas medicinales.'],
      ['Apocynaceae','Gentianales','🌺','#7e52c4','falso laurel y vinca',['Árboles, arbustos, hierbas o lianas','Muchas especies producen látex blanco','Flores radiales y vistosas','Pétalos, sépalos y estambres usualmente en número de cinco','Corola gamopétala, con forma de trompeta o estrella','Frutos carnosos o secos, bayas o drupas'],['alimenticio','madera','medicina','ornamental'],['Nerium oleander · falso laurel','Vinca sp. · vinca'],'Dato importante: varias especies son ornamentales, pero el látex de algunas puede contener compuestos activos; por eso se estudian y se manejan con cuidado.'],
      ['Araceae','Alismatales','🌿','#2978a0','cartucho, costilla de Adán y anturios',['Plantas herbáceas, epífitas, hemiepífitas o lianas','Algunas son acuáticas o tuberosas','Hojas generalmente sagitadas, enteras o divididas','Pecíolo envainador','Inflorescencia formada por espata y espádice','Fruto tipo baya'],['alimenticio','cestería','medicinal','ornamental','perfumería','utensilios'],['Zantedeschia aethiopica · cartucho','Monstera spp. · costilla de Adán','Anthurium spp. · anturios'],'Dato importante: es una familia muy visible en jardines y floristerías por sus hojas grandes y sus inflorescencias con espata y espádice.'],
      ['Araliaceae','Apiales','🍃','#4a8f3a','hiedra y puma maki',['Árboles, arbustos o hemiepífitas','Hojas simples, alternas o compuestas','Nervaduras prominentes','Estípulas prominentes','Madera ligera','Fruto tipo drupa'],['artesanías','leña','madera','medicina','ornamental','utensilios'],['Hedera helix · hiedra','Oreopanax ecuadorensis · puma maki'],'Dato importante: combina especies trepadoras y arbóreas; varias se reconocen por su follaje ornamental y frutos en drupa.'],
      ['Arecaceae','Arecales','🌴','#b28a00','chonta, pambil, tagua y palma de ramos',['Árboles, arbustos y lianas, algunas espinosas','Tronco uniforme tipo estípite','Hojas envainadoras con pecíolo acanalado','Láminas generalmente pinnadas','Flores crema con piezas de tres','Fruto drupa fibrosa o baya'],['alimento','cestería','construcción','escobas','leña','medicina','ornamental','rituales'],['Bactris gasipaes · chonta/contaduro','Iriartea deltoidea · pambil','Phytelephas aequatorialis · tagua','Ceroxylon sp. · palma de ramos','Mauritia flexuosa · morete','Oenocarpus bataua · unguragua'],'Dato importante: la tagua produce “marfil vegetal”; el pambil es usado en construcciones amazónicas y la chonta es importante en celebraciones de comunidades amazónicas.'],
      ['Asteraceae','Asterales','🌻','#55779d','girasol, gazania y diente de león',['Compositae es su nombre antiguo','Hierbas, arbustos o árboles','Hojas simples o compuestas','Inflorescencia en capítulo sostenida por receptáculo','Flores liguladas o tubulares','Fruto en aquenio'],['alimento','forraje','medicina','ornamental','rituales','comercial'],['Helianthus annuus · girasol','Taraxacum officinale · diente de león','Gazania sp.','Chrysanthemum sp.','Chuquiraga jussieui · chuquiragua'],'Dato importante: lo que parece una sola flor muchas veces es un capítulo formado por numerosas flores pequeñas; por eso es una familia clave para explicar inflorescencias.']
    ]
  },
  {
    id: 'lamina-2', title: 'Lámina 2', source: 'ANGIOSPERMAS 2.pdf', accent: '#0ea5e9',
    description: 'Once familias representativas con énfasis en Lamiales, Poales, Caryophyllales, Cucurbitales y Malpighiales.',
    families: [
      ['Bignoniaceae','Lamiales','🌼','#c79b19','guayacán y cholán',['Árboles o lianas, a veces hemiepífitas','Hojas simples o compuestas','Pueden presentar zarcillos cuando son trepadoras','Inflorescencias racimosas, paniculadas o solitarias','Flores grandes y conspicuas','Fruto indehiscente o tipo vaina endurecida'],['artesanía','cuerda','colorantes','leña','madera','medicina','ornamental','rituales'],['Tabebuia chrysantha · guayacán','Tecoma stans · cholán'],'Dato importante: el guayacán es apreciado por su floración amarilla en Zapotillo y por su madera dura, aunque se valora más conservado que talado.'],
      ['Boraginaceae','Boraginales','💠','#5578be','borraja y araña caspi',['Hierbas, arbustos, árboles o lianas','Hojas simples y alternas, frecuentemente sin estípulas','Inflorescencia escorpioide o cima circinada','Flores regulares y tubulares','Ovario súpero','Fruto drupáceo o esquizocarpo de cuatro núculas'],['apicultura','comercial','leña','madera','medicinal','ornamental'],['Borago officinalis · borraja','Cordia nodosa · araña caspi'],'Dato importante: Cordia nodosa aparece en el material como especie de interés antiofídico en la Amazonía ecuatoriana.'],
      ['Brassicaceae','Brassicales','🥬','#e75b6b','nabo y rábano',['Cruciferae es su nombre antiguo','Generalmente herbáceas, anuales, bienales o perennes','Hojas simples o compuestas, alternas y sin estípulas','Raíces a veces engrosadas o tuberosas','Perianto en forma de cruz','Ovario súpero'],['alimenticio','artesanal','comercial','forraje','medicinal','ornamental','floristería'],['Brassica napus · nabo','Raphanus sativus · rábano'],'Dato importante: nabo y rábano se destacan por raíces comestibles, fáciles de cultivar y de cosecha rápida.'],
      ['Bromeliaceae','Poales','🍍','#9a8d28','piñuela y achupalla',['Hierbas o arbustos usualmente epífitas','Hojas simples, a menudo en roseta','Tricomas o escamas peltadas','Reserva de agua en sus rosetas','Brácteas florales a menudo coloreadas','Semillas aladas o plumosas'],['alimento','artesanal','cercas','floristería','forraje','medicinal','ornamental'],['Bromelia pinguin · piñuela/piña de ratón','Puya hamata · achupalla'],'Dato importante: Puya hamata es propia del páramo, ayuda a conservar humedad en el suelo y sirve de alimento natural para el oso andino.'],
      ['Burseraceae','Sapindales','🪵','#d16b3c','palo santo',['Árboles','Resina con olor fuerte similar a gasolina','Hojas compuestas imparipinnadas sin estípulas','Inflorescencia panícula o racimosa','Flores pequeñas y regulares','Fruto drupáceo o capsular'],['alimento','comercial','leña','madera','medicinal','ritual'],['Bursera graveolens · palo santo'],'Dato importante: el palo santo es típico del bosque seco tropical; su uso como incienso debe manejarse de forma sostenible.'],
      ['Cactaceae','Caryophyllales','🌵','#508f4b','San Pedro, tuna y pitahaya',['Arbustos suculentos, árboles o lianas','Tallos carnosos, aplanados o acostillados','Hojas deciduas modificadas en espinas','Flores solitarias y usualmente bisexuales','Estambres numerosos','Fruto tipo baya'],['alimenticio','cercas','comercial','medicinal','ornamental','ritual'],['Echinopsis pachanoi · San Pedro','Opuntia soederstromiana · tuna/nopal','Selenicereus megalanthus · pitahaya amarilla'],'Dato importante: su adaptación más evidente es la suculencia del tallo y la transformación de hojas en espinas, útil para reducir pérdida de agua.'],
      ['Caricaceae','Brassicales','🍈','#f08a24','papaya y babaco',['Árboles o arbustos dioicos','Látex abundante','Hojas alternas simples','Hojas palmatilobuladas','Fruto baya carnosa y agrandada'],['alimenticio','comercial','medicinal'],['Carica papaya · papaya','Vasconcellea heilbornii · babaco'],'Dato importante: la papaya y el babaco muestran la importancia alimenticia de esta familia en regiones tropicales y andinas.'],
      ['Cucurbitaceae','Cucurbitales','🎃','#069477','pepino, zapallo, chayote y sandía',['Hierbas con tallo blando','Presencia de zarcillos','Hojas alternas simples o palmeadas','Flores unisexuales','Ovario ínfero','Fruto baya tipo pepónide'],['alimenticio','comercial','medicinal','ritual','ornamental'],['Cucumis sativus · pepino','Cucurbita pepo · zapallo','Sechium edule · chayote','Citrullus lanatus · sandía','Cucurbita maxima · calabaza','Cyclanthera pedata · achocha'],'Dato importante: es una familia muy útil para explicar frutos pepónides, como sandía, zapallo, pepino y calabaza.'],
      ['Cyperaceae','Poales','🌱','#6b8e23','ciperáceas',['Hierbas generalmente de zonas húmedas','Tallos frecuentemente triangulares','Hojas estrechas y alternas','Inflorescencias en espiguillas','Fruto seco tipo aquenio'],['artesanal','forraje','ornamental','medicinal'],['Cyperus sp.','Carex sp.'],'Dato importante: se parece a las gramíneas, pero muchas ciperáceas se reconocen por tallos triangulares y hábitats húmedos.'],
      ['Ericaceae','Ericales','🫐','#8b5cf6','mortiño y ericáceas',['Arbustos o pequeños árboles','Hojas simples, coriáceas o perennes','Flores vistosas, a menudo urceoladas','Frutos tipo baya o cápsula'],['alimenticio','medicinal','ornamental'],['Vaccinium floribundum · mortiño','Gaultheria sp.'],'Dato importante: varias ericáceas de páramo producen frutos comestibles y son relevantes para ecosistemas altoandinos.'],
      ['Euphorbiaceae','Malpighiales','🍃','#c13b7a','flor de Navidad, lechero y caucho',['Hierbas, arbustos o árboles con látex','Hojas alternas simples o palmaticompuestas','Flores unisexuales','A veces presentan ciátios','Fruto capsular o drupáceo'],['alimento','medicinal','madera','ornamental','ritual'],['Euphorbia pulcherrima · flor de Navidad','Euphorbia laurifolia · lechero','Hevea brasiliensis · caucho'],'Dato importante: Hevea brasiliensis es relevante por el caucho natural, mientras Euphorbia pulcherrima es muy usada como ornamental.']
    ]
  },
  {
    id: 'lamina-3', title: 'Lámina 3', source: 'ANGIOSPERMAS 3.pdf', accent: '#22c55e',
    description: 'Doce familias representativas de distintos órdenes con importancia ecológica, ornamental y alimenticia.',
    families: [
      ['Fabaceae','Fabales','🫘','#2f855a','leguminosas, guaba y mimosa',['Leguminosae es su nombre antiguo','Hojas compuestas con estípulas','Inflorescencia variada','Flores hermafroditas','Fruto vaina o legumbre','Incluye subfamilias como Faboideae, Mimosoideae y Caesalpinioideae'],['alimento','forraje','cercas vivas','leña','madera','medicina','ornamental'],['Inga edulis · guaba','Phaseolus vulgaris · fréjol','Vicia faba · haba','Pisum sativum · arveja','Mimosa pudica · sensitiva','Brownea grandiceps · cruz kaspi'],'Dato importante: las leguminosas son claves en alimentación por proteínas, fibra y minerales; además muchas fijan nitrógeno y ayudan al suelo.'],
      ['Gentianaceae','Gentianales','💙','#2563eb','simorra',['Hierbas anuales o perennes, arbustos o saprófitas','Hojas simples, opuestas o decusadas','Inflorescencia terminal o axilar','Presencia de brácteas o bractéolas','Fruto cápsula bivalvada'],['forraje','medicina','ornamental'],['Macrocarpaea sp. · simorra'],'Dato importante: el material destaca Macrocarpaea sp. como arbusto amazónico; la familia posee flores atractivas y valor ornamental.'],
      ['Geraniaceae','Geraniales','🌸','#c026d3','geranios',['Usualmente hierbas o subarbustos','Hojas alternas u opuestas con aceites aromáticos','Bordes enteros o serrados','Flores usualmente bisexuales','Sépalos y pétalos normalmente de cinco','Fruto esquizocarpo o cápsula loculicida'],['forraje','comercio','medicina','ornamental'],['Geranium ecuadoriense · San Pedro','Geranium diffusum · San Pedro','Geranium antisanae','Pelargonium x domesticum · geranio pensamiento','Pelargonium x hortorum · geranio rojo'],'Dato importante: el PDF menciona especies endémicas de Ecuador asociadas a páramos y zonas altoandinas como Chimborazo y Antisana.'],
      ['Gesneriaceae','Lamiales','🌺','#d9467a','chukchu watana y orquilla',['Hierbas, arbustos, epífitas o hemiepífitas','Hojas usualmente simples y opuestas','Pueden formar rosetas','Flores vistosas y bisexuales','Estambres 2+2','Fruto cápsula loculicida, septicida o baya'],['comercio','medicina','ornamental'],['Drymonia coccinea · chukchu watana','Hepiella ulmifolia · orquilla'],'Dato importante: el material menciona 81 especies endémicas, lo que vuelve a la familia importante para conservación y ornamentación.'],
      ['Heliconiaceae','Zingiberales','🦜','#dc2626','heliconias',['Hierbas con pseudotallos formados por vainas de pecíolos','Hojas largas, alternas y enteras','Inflorescencias erectas o pendientes','Brácteas vistosas','Flores bisexuales y zigomorfas','Fruto baya alargada o globosa'],['cacería','comercial','floristería','medicinal','ornamental','utensilios de cocina'],['Heliconia episcopalis · penoca','Heliconia rostrata'],'Dato importante: las heliconias atraen colibríes, que colaboran en la polinización; por sus colores se usan mucho en floristería.'],
      ['Iridaceae','Asparagales','🌷','#4f46e5','iris y plantas con rizomas',['Hierbas con rizomas, cormos o bulbos','Hojas alternas, generalmente estrechas','Flores vistosas con piezas florales de tres','Fruto cápsula','Órganos subterráneos de reserva'],['ornamental','medicinal','comercial'],['Iris sp.','Crocosmia sp.'],'Dato importante: muchas iridáceas son ornamentales por sus flores llamativas y por la facilidad de propagación mediante bulbos o rizomas.'],
      ['Lamiaceae','Lamiales','🌿','#059669','menta, albahaca y salvia',['Hierbas o arbustos aromáticos','Tallos frecuentemente cuadrangulares','Hojas opuestas','Flores bilabiadas','Presencia de aceites esenciales'],['alimenticio','medicinal','aromático','ornamental'],['Mentha sp. · menta','Ocimum basilicum · albahaca','Salvia sp.'],'Dato importante: es una familia útil para explicar plantas aromáticas; muchas especies se usan en cocina y medicina tradicional.'],
      ['Lauraceae','Laurales','🥑','#65a30d','aguacate y laurel',['Árboles o arbustos aromáticos','Hojas simples, alternas y coriáceas','Flores pequeñas','Fruto drupa o baya','Presencia de aceites esenciales'],['alimenticio','madera','medicina','aromático'],['Persea americana · aguacate','Laurus nobilis · laurel'],'Dato importante: combina especies alimenticias como el aguacate y aromáticas como el laurel, por eso tiene valor económico y culinario.'],
      ['Malvaceae','Malvales','🌺','#e11d48','hibisco, cacao y algodón',['Árboles, arbustos o hierbas','Hojas simples, a menudo palmatinervias','Flores vistosas','Numerosos estambres','Fruto cápsula, baya o esquizocarpo'],['alimenticio','fibra','madera','medicinal','ornamental'],['Theobroma cacao · cacao','Gossypium sp. · algodón','Hibiscus rosa-sinensis · hibisco'],'Dato importante: es una familia de alto impacto económico porque incluye cacao, algodón y ornamentales como el hibisco.'],
      ['Malpighiaceae','Malpighiales','🌼','#f59e0b','acerola y lianas',['Árboles, arbustos o lianas','Hojas simples y opuestas','Flores vistosas, frecuentemente amarillas o rosadas','Fruto seco o carnoso'],['alimenticio','medicinal','ornamental'],['Malpighia emarginata · acerola','Banisteriopsis sp.'],'Dato importante: muchas especies tropicales son lianas o arbustos con flores llamativas; algunas tienen frutos comestibles ricos en vitamina C.'],
      ['Moraceae','Rosales','🍞','#7c2d12','higo, mora y árbol de pan',['Árboles, arbustos o lianas con látex','Hojas simples','Flores pequeñas en inflorescencias compactas','Frutos agregados o múltiples'],['alimenticio','madera','medicinal','ornamental'],['Ficus carica · higo','Morus sp. · mora','Artocarpus altilis · árbol de pan'],'Dato importante: se reconoce por la presencia de látex y por estructuras de fruto múltiple, como higos y árbol de pan.'],
      ['Myrtaceae','Myrtales','🍃','#0f766e','guayaba y eucalipto',['Árboles o arbustos aromáticos','Hojas simples con aceites esenciales','Flores con numerosos estambres','Fruto baya, cápsula o drupa'],['alimenticio','medicina','madera','aromático','ornamental'],['Psidium guajava · guayaba','Eucalyptus sp. · eucalipto'],'Dato importante: sus aceites esenciales y frutos comestibles hacen que sea importante en medicina, alimentación y usos maderables.']
    ]
  }
].map(l => ({ ...l, families: l.families.map(([family,order,icon,color,image,traits,uses,reps,note]) => ({family,order,icon,color,image,traits,uses,reps,note,orderInfo: orderInfo[order]})) }));

function BotanicalArt({ family, icon, color }) {
  return <div className="art" style={{ '--c': color }}><div className="artGlow"/><div className="stem"/><span className="leaf l1">{icon}</span><span className="leaf l2">{icon}</span><span className="leaf l3">{icon}</span><div className="artLabel">{family}</div></div>;
}
function FamilyCard({ item, index, onOpen }) {
  return <motion.button layout initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:index*.035}} className="familyCard" style={{'--c':item.color}} onClick={() => onOpen(item)}>
    <div className="cardTop"><div className="number">{index+1}</div><div className="order">Orden: {item.order}</div></div>
    <div className="cardBody"><div><h3>{item.family}</h3><p className="imageNote">{item.image}</p><div className="mini"><strong>Características principales</strong><p>{item.traits.slice(0,3).join('. ')}.</p></div><div className="chips">{item.uses.slice(0,4).map(use => <span key={use}>{use}</span>)}</div></div><BotanicalArt family={item.family} icon={item.icon} color={item.color}/></div>
    <div className="openRow">Ver ficha completa <ChevronRight size={16}/></div>
  </motion.button>;
}
function DetailModal({ selected, onClose }) {
  return <AnimatePresence>{selected && <motion.div className="modalBackdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}><motion.article className="modal" initial={{scale:.94,y:20,opacity:0}} animate={{scale:1,y:0,opacity:1}} exit={{scale:.94,y:20,opacity:0}} onClick={e=>e.stopPropagation()} style={{'--c':selected.color}}><button className="close" onClick={onClose}><X size={20}/></button><div className="modalHead"><BotanicalArt family={selected.family} icon={selected.icon} color={selected.color}/><div><p className="modalOrder">Orden {selected.order}</p><h2>{selected.family}</h2><p>{selected.note}</p></div></div><div className="modalGrid"><section><h4>Características de la familia</h4>{selected.traits.map(x => <p key={x}>• {x}</p>)}</section><section><h4>Características del orden</h4><p>{selected.orderInfo}</p></section><section><h4>Usos principales</h4><div className="chips big">{selected.uses.map(x => <span key={x}>{x}</span>)}</div></section><section><h4>Dato para exponer</h4><p>{selected.note}</p></section><section className="wide"><h4>Especies representativas del material</h4><div className="repGrid">{selected.reps.map(x => <div key={x} className="rep">{selected.icon} {x}</div>)}</div></section></div></motion.article></motion.div>}</AnimatePresence>;
}
export default function App(){
  const [active,setActive]=useState(laminas[0].id),[query,setQuery]=useState(''),[order,setOrder]=useState('Todos'),[selected,setSelected]=useState(null),[presentation,setPresentation]=useState(false);
  const lamina=laminas.find(l=>l.id===active);
  const orders=useMemo(()=>['Todos',...Array.from(new Set(lamina.families.map(f=>f.order))).sort()],[lamina]);
  const filtered=lamina.families.filter(f=>`${f.family} ${f.order} ${f.reps.join(' ')} ${f.uses.join(' ')} ${f.traits.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (order==='Todos'||f.order===order));
  return <main className={presentation?'presentation app':'app'}><section className="hero"><div className="heroBg"/><div className="badge"><Sparkles size={16}/> APG IV · Angiospermas</div><h1>Esquema Taxonómico de Angiospermas Representativas</h1><p className="heroText">Infografía web interactiva para exposición: explora familias, órdenes, características, usos, datos importantes y especies representativas de los tres documentos.</p><div className="heroActions"><button onClick={()=>setPresentation(!presentation)}><Presentation size={18}/>{presentation?'Salir de presentación':'Modo presentación'}</button><a href="#laminas"><BookOpen size={18}/> Ver láminas</a></div></section><section id="laminas" className="workspace"><div className="tabs">{laminas.map(l=><button key={l.id} onClick={()=>{setActive(l.id);setOrder('Todos');setQuery('')}} className={active===l.id?'active':''} style={{'--c':l.accent}}><span>{l.title}</span><small>{l.families.length} familias</small></button>)}</div><div className="panelHead"><div><p className="source"><Sprout size={16}/> {lamina.source}</p><h2>{lamina.title}: familias representativas</h2><p>{lamina.description}</p></div><div className="centerOrb" style={{'--c':lamina.accent}}><span>APG IV</span><strong>{lamina.families.length}</strong><small>familias</small></div></div><div className="tools"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar familia, orden, uso, característica o especie..."/></label><label><Filter size={18}/><select value={order} onChange={e=>setOrder(e.target.value)}>{orders.map(o=><option key={o}>{o}</option>)}</select></label></div><div className="taxonomyMap"><div className="hub" style={{'--c':lamina.accent}}><Leaf/><b>APG IV</b><span>{lamina.title}</span></div><div className="cardsGrid">{filtered.map((item,i)=><FamilyCard key={item.family} item={item} index={i} onOpen={setSelected}/>)}</div></div></section><section className="explain"><Layers3 size={22}/><div><h3>Cómo presentarlo</h3><p>Selecciona una lámina, filtra por orden y abre cada tarjeta. En la ficha completa encontrarás características del orden, características de la familia, especies representativas, usos y un dato importante listo para decir en la exposición.</p></div></section><footer>Diseño interactivo para presentación académica · Familias de angiospermas APG IV</footer><DetailModal selected={selected} onClose={()=>setSelected(null)}/></main>;
}
