import React, { useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, Leaf, Sparkles, BookOpen, Presentation, X, ChevronRight, Sprout, Filter } from 'lucide-react';

const laminas = [
  {
    id: 'lamina-1', title: 'Lámina 1', source: 'ANGIOSPERMAS 1.pdf · desde página 20', accent: '#7c3aed',
    description: 'Nueve familias representativas organizadas por orden, rasgos botánicos, usos y especies destacadas.',
    families: [
      ['Amaranthaceae','Caryophyllales','🌾','#9f2d5f','amaranto, quinoa, espinaca y paico',['Hierbas, arbustos o trepadoras','Hojas simples, alternas u opuestas, sin estípulas','Inflorescencia paniculada','Fruto utrículo seco o cápsula'],['alimenticio','colorante','forraje','medicinal','ornamental'],['Amaranthus · amaranto','Chenopodium quinoa · quinoa','Spinacia oleracea · espinaca','Cyathula ambrosioides · paico'],'Familia de gran valor alimenticio y medicinal; incluye especies consumidas ampliamente como la quinoa y la espinaca.'],
      ['Anacardiaceae','Sapindales','🥭','#c86b1e','mango, cajú, molle y ovo',['Árboles, arbustos o lianas','Exudado resinoso que puede oscurecerse','Hojas alternas, simples o compuestas','Fruto tipo drupa'],['alimenticio','comercial','especiería','madera','medicinal','ornamental'],['Mangifera indica · mango','Anacardium occidentale · cajú','Schinus molle · molle','Spondias purpurea · ovo'],'Agrupa especies de frutos conocidos y árboles con resinas aromáticas o de interés comercial.'],
      ['Annonaceae','Magnoliales','🍈','#4d7c39','guanábana y chirimoya',['Árboles, arbustos o lianas','Hojas alternas, simples, enteras y aromáticas','Flores verdosas o amarillentas','Fruto agregado de bayas o monocarpos'],['alimenticio','artesanal','construcción','madera','medicinal','ornamental'],['Annona muricata · guanábana','Annona cherimola · chirimoya'],'Destaca por frutos tropicales comestibles de gran importancia en costa, sierra y amazonía.'],
      ['Apiaceae','Apiales','☘️','#0f9f8f','apio y perejil',['Hierbas, arbustos o árboles con entrenudos huecos','Hojas disectas o divididas con pecíolo envainado','Inflorescencia en umbela','Fruto tipo esquizocarpo'],['alimenticio','comercial','construcción','forraje','medicina'],['Apium graveolens · apio','Petroselinum crispum · perejil'],'Se reconoce fácilmente por sus umbelas y por especies usadas como condimentos y alimentos.'],
      ['Apocynaceae','Gentianales','🌺','#7e52c4','falso laurel y vinca',['Árboles, arbustos, hierbas o lianas','Muchas especies presentan látex blanco','Flores radiales y vistosas','Corola gamopétala; frutos carnosos o secos'],['alimenticio','madera','medicina','ornamental'],['Nerium oleander · falso laurel','Vinca sp. · vinca'],'Familia llamativa por sus flores ornamentales y por la presencia de látex en varias especies.'],
      ['Araceae','Alismatales','🌿','#2978a0','cartucho, costilla de Adán y anturios',['Herbáceas, epífitas, hemiepífitas o lianas','Hojas generalmente sagitadas o divididas','Inflorescencia con espata y espádice','Fruto tipo baya'],['alimenticio','cestería','medicinal','ornamental','perfumería'],['Zantedeschia aethiopica · cartucho','Monstera spp. · costilla de Adán','Anthurium spp. · anturios'],'Muy usada en ornamentación por sus hojas grandes y estructuras florales vistosas.'],
      ['Araliaceae','Apiales','🍃','#4a8f3a','hiedra y puma maki',['Árboles, arbustos o hemiepífitas','Hojas simples, alternas o compuestas','Nervaduras y estípulas prominentes','Fruto tipo drupa'],['artesanías','leña','madera','medicina','ornamental'],['Hedera helix · hiedra','Oreopanax ecuadorensis · puma maki'],'Incluye especies trepadoras y arbóreas reconocidas por su follaje y frutos en drupa.'],
      ['Arecaceae','Arecales','🌴','#b28a00','chonta, pambil, tagua y palma de ramos',['Árboles, arbustos y lianas, algunas espinosas','Tronco uniforme tipo estípite','Hojas generalmente pinnadas','Flores crema; fruto drupa o baya'],['alimento','cestería','construcción','leña','medicina','ornamental','rituales'],['Bactris gasipaes · chonta/contaduro','Iriartea deltoidea · pambil','Phytelephas aequatorialis · tagua','Ceroxylon sp. · palma de ramos'],'Familia clave por sus usos alimenticios, constructivos y artesanales, como la tagua o marfil vegetal.'],
      ['Asteraceae','Asterales','🌻','#55779d','girasol, gazania y diente de león',['Hierbas, arbustos o árboles','Hojas simples o compuestas','Inflorescencia en capítulo','Flores liguladas o tubulares; fruto aquenio'],['alimento','forraje','medicina','ornamental','rituales'],['Helianthus annuus · girasol','Taraxacum officinale · diente de león','Gazania sp.','Chrysanthemum sp.','Chuquiraga jussieui · chuquiragua'],'Una de las familias más reconocibles por sus capítulos florales.']
    ]
  },
  {
    id: 'lamina-2', title: 'Lámina 2', source: 'ANGIOSPERMAS 2.pdf', accent: '#0ea5e9',
    description: 'Once familias representativas con énfasis en Lamiales, Poales, Caryophyllales, Cucurbitales y Malpighiales.',
    families: [
      ['Bignoniaceae','Lamiales','🌼','#c79b19','guayacán y cholán',['Árboles o lianas, a veces hemiepífitas','Hojas simples o compuestas','Flores grandes y conspicuas','Fruto tipo vaina endurecida'],['artesanía','cuerda','colorantes','leña','madera','medicina','ornamental'],['Tabebuia chrysantha · guayacán','Tecoma stans · cholán'],'Destaca por árboles de floración amarilla y gran valor ornamental y maderable.'],
      ['Boraginaceae','Boraginales','💠','#5578be','borraja y araña caspi',['Hierbas, arbustos, árboles o lianas','Hojas simples y alternas, sin estípulas','Inflorescencia escorpioide','Fruto drupáceo o esquizocarpo'],['apicultura','comercial','leña','madera','medicinal','ornamental'],['Borago officinalis · borraja','Cordia nodosa · araña caspi'],'En Galápagos presenta alto endemismo y varias especies de interés medicinal.'],
      ['Brassicaceae','Brassicales','🥬','#e75b6b','nabo y rábano',['Generalmente herbáceas','Hojas alternas, simples o compuestas','Perianto en forma de cruz','Fruto baya o cápsula'],['alimenticio','artesanal','comercial','forraje','medicinal','ornamental'],['Brassica napus · nabo','Raphanus sativus · rábano'],'Conocida como Cruciferae por sus flores en forma de cruz.'],
      ['Bromeliaceae','Poales','🍍','#9a8d28','piñuela y achupalla',['Hierbas o arbustos usualmente epífitas','Hojas en roseta con tricomas','Reserva de agua en las rosetas','Fruto cápsula o baya'],['alimento','artesanal','cercas','floristería','medicinal','ornamental'],['Bromelia pinguin · piñuela','Puya hamata · achupalla'],'Propias de América, frecuentes en zonas tropicales y de páramo.'],
      ['Burseraceae','Sapindales','🪵','#d16b3c','palo santo',['Árboles con resina de olor fuerte','Hojas compuestas imparipinnadas','Flores pequeñas y regulares','Fruto drupáceo o capsular'],['alimento','comercial','leña','madera','medicinal','ritual'],['Bursera graveolens · palo santo'],'El palo santo es típico del bosque seco tropical y se usa como incienso.'],
      ['Cactaceae','Caryophyllales','🌵','#508f4b','San Pedro, tuna y pitahaya',['Arbustos suculentos, árboles o lianas','Tallos carnosos o acostillados','Hojas modificadas en espinas','Flores solitarias; fruto baya'],['alimenticio','cercas','comercial','medicinal','ornamental','ritual'],['Echinopsis pachanoi · San Pedro','Opuntia soederstromiana · tuna/nopal','Selenicereus megalanthus · pitahaya amarilla'],'Familia adaptada a ambientes secos, con usos alimenticios y rituales.'],
      ['Caricaceae','Brassicales','🍈','#f08a24','papaya y babaco',['Árboles o arbustos dioicos','Látex abundante','Hojas alternas palmatilobuladas','Fruto baya carnosa'],['alimenticio','comercial','medicinal'],['Carica papaya · papaya','Vasconcellea heilbornii · babaco'],'Familia tropical muy conocida por frutos carnosos comestibles.'],
      ['Cucurbitaceae','Cucurbitales','🎃','#069477','pepino, zapallo, chayote y sandía',['Hierbas con tallo blando y zarcillos','Hojas alternas simples o palmeadas','Flores unisexuales','Fruto baya tipo pepónide'],['alimenticio','comercial','medicinal','ritual','ornamental'],['Cucumis sativus · pepino','Cucurbita pepo · zapallo','Sechium edule · chayote','Citrullus lanatus · sandía'],'Agrupa frutos agrícolas muy conocidos.'],
      ['Cyperaceae','Poales','🌱','#6b8e23','ciperáceas',['Hierbas con tallos frecuentemente triangulares','Hojas estrechas y alternas','Inflorescencias en espiguillas','Fruto seco tipo aquenio'],['artesanal','forraje','ornamental','medicinal'],['Cyperus sp.','Carex sp.'],'Se reconoce por tallos triangulares y presencia en zonas húmedas.'],
      ['Ericaceae','Ericales','🫐','#8b5cf6','mortiño y ericáceas',['Arbustos o pequeños árboles','Hojas simples, coriáceas o perennes','Flores vistosas','Frutos tipo baya o cápsula'],['alimenticio','medicinal','ornamental'],['Vaccinium floribundum · mortiño','Gaultheria sp.'],'Incluye especies de páramo con frutos comestibles y valor ecológico.'],
      ['Euphorbiaceae','Malpighiales','🍃','#c13b7a','flor de Navidad, lechero y caucho',['Hierbas, arbustos o árboles con látex','Hojas alternas simples o compuestas','Flores unisexuales','Fruto capsular o drupáceo'],['alimento','medicinal','madera','ornamental','ritual'],['Euphorbia pulcherrima · flor de Navidad','Euphorbia laurifolia · lechero','Hevea brasiliensis · caucho'],'Importante por especies ornamentales y por el caucho natural.']
    ]
  },
  {
    id: 'lamina-3', title: 'Lámina 3', source: 'ANGIOSPERMAS 3.pdf', accent: '#22c55e',
    description: 'Doce familias representativas de distintos órdenes con importancia ecológica, ornamental y alimenticia.',
    families: [
      ['Fabaceae','Fabales','🫘','#2f855a','leguminosas, guaba y mimosa',['Leguminosae es su nombre antiguo','Hojas compuestas con estípulas','Inflorescencia variada','Fruto vaina o legumbre'],['alimento','forraje','cercas vivas','leña','madera','medicina','ornamental'],['Inga edulis · guaba','Phaseolus vulgaris · fréjol','Vicia faba · haba','Mimosa pudica · sensitiva'],'Clave por su aporte alimenticio y por la fijación de nitrógeno.'],
      ['Gentianaceae','Gentianales','💙','#2563eb','simorra',['Hierbas, arbustos o saprófitas','Hojas simples, opuestas o decusadas','Inflorescencia terminal o axilar','Fruto cápsula bivalvada'],['forraje','medicina','ornamental'],['Macrocarpaea sp. · simorra'],'Incluye arbustos amazónicos y plantas de flores llamativas.'],
      ['Geraniaceae','Geraniales','🌸','#c026d3','geranios',['Hierbas o subarbustos','Hojas con aceites aromáticos','Flores bisexuales','Fruto esquizocarpo o cápsula'],['forraje','comercio','medicina','ornamental'],['Geranium ecuadoriense · San Pedro','Pelargonium x domesticum · geranio pensamiento','Pelargonium x hortorum · geranio rojo'],'Destaca por especies endémicas y ornamentales.'],
      ['Gesneriaceae','Lamiales','🌺','#d9467a','chukchu watana y orquilla',['Hierbas, arbustos, epífitas o hemiepífitas','Hojas simples y opuestas','Flores vistosas y bisexuales','Fruto cápsula o baya'],['comercio','medicina','ornamental'],['Drymonia coccinea · chukchu watana','Hepiella ulmifolia · orquilla'],'Familia ornamental con numerosas especies endémicas.'],
      ['Heliconiaceae','Zingiberales','🦜','#dc2626','heliconias',['Hierbas con pseudotallos','Hojas largas, alternas y enteras','Inflorescencias con brácteas vistosas','Fruto baya'],['cacería','comercial','floristería','medicinal','ornamental'],['Heliconia episcopalis · penoca','Heliconia rostrata'],'Sus brácteas coloridas atraen colibríes y se usan en floristería.'],
      ['Iridaceae','Asparagales','🌷','#4f46e5','iris y plantas con rizomas',['Hierbas con rizomas, cormos o bulbos','Hojas alternas y estrechas','Flores vistosas con piezas de tres','Fruto cápsula'],['ornamental','medicinal','comercial'],['Iris sp.','Crocosmia sp.'],'Reconocida por flores ornamentales y órganos subterráneos de reserva.'],
      ['Lamiaceae','Lamiales','🌿','#059669','menta, albahaca y salvia',['Hierbas o arbustos aromáticos','Tallos frecuentemente cuadrangulares','Hojas opuestas','Flores bilabiadas y aceites esenciales'],['alimenticio','medicinal','aromático','ornamental'],['Mentha sp. · menta','Ocimum basilicum · albahaca','Salvia sp.'],'Conocida por plantas aromáticas usadas en cocina y medicina tradicional.'],
      ['Lauraceae','Laurales','🥑','#65a30d','aguacate y laurel',['Árboles o arbustos aromáticos','Hojas simples, alternas y coriáceas','Flores pequeñas','Fruto drupa o baya'],['alimenticio','madera','medicina','aromático'],['Persea americana · aguacate','Laurus nobilis · laurel'],'Incluye especies alimenticias y aromáticas de alto valor económico.'],
      ['Malvaceae','Malvales','🌺','#e11d48','hibisco, cacao y algodón',['Árboles, arbustos o hierbas','Hojas simples y palmatinervias','Flores vistosas con numerosos estambres','Fruto cápsula, baya o esquizocarpo'],['alimenticio','fibra','madera','medicinal','ornamental'],['Theobroma cacao · cacao','Gossypium sp. · algodón','Hibiscus rosa-sinensis · hibisco'],'Agrupa plantas de importancia económica como cacao y algodón.'],
      ['Malpighiaceae','Malpighiales','🌼','#f59e0b','acerola y lianas',['Árboles, arbustos o lianas','Hojas simples y opuestas','Flores vistosas','Fruto seco o carnoso'],['alimenticio','medicinal','ornamental'],['Malpighia emarginata · acerola','Banisteriopsis sp.'],'Incluye lianas y arbustos tropicales de flores llamativas.'],
      ['Moraceae','Rosales','🍞','#7c2d12','higo, mora y árbol de pan',['Árboles, arbustos o lianas con látex','Hojas simples','Flores pequeñas en inflorescencias compactas','Frutos agregados o múltiples'],['alimenticio','madera','medicinal','ornamental'],['Ficus carica · higo','Morus sp. · mora','Artocarpus altilis · árbol de pan'],'Reconocida por frutos múltiples y presencia de látex.'],
      ['Myrtaceae','Myrtales','🍃','#0f766e','guayaba y eucalipto',['Árboles o arbustos aromáticos','Hojas con aceites esenciales','Flores con numerosos estambres','Fruto baya, cápsula o drupa'],['alimenticio','medicina','madera','aromático','ornamental'],['Psidium guajava · guayaba','Eucalyptus sp. · eucalipto'],'Importante por frutos comestibles, aceites esenciales y especies maderables.']
    ]
  }
].map(l => ({ ...l, families: l.families.map(([family,order,icon,color,image,traits,uses,reps,note]) => ({family,order,icon,color,image,traits,uses,reps,note})) }));

function BotanicalArt({ family, icon, color }) {
  return <div className="art" style={{ '--c': color }}><div className="artGlow"/><div className="stem"/><span className="leaf l1">{icon}</span><span className="leaf l2">{icon}</span><span className="leaf l3">{icon}</span><div className="artLabel">{family}</div></div>;
}
function FamilyCard({ item, index, onOpen }) {
  return <motion.button layout initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:index*.035}} className="familyCard" style={{'--c':item.color}} onClick={() => onOpen(item)}>
    <div className="cardTop"><div className="number">{index+1}</div><div className="order">Orden: {item.order}</div></div>
    <div className="cardBody"><div><h3>{item.family}</h3><p className="imageNote">{item.image}</p><div className="mini"><strong>Características</strong><p>{item.traits.slice(0,2).join('. ')}.</p></div><div className="chips">{item.uses.slice(0,3).map(use => <span key={use}>{use}</span>)}</div></div><BotanicalArt family={item.family} icon={item.icon} color={item.color}/></div>
    <div className="openRow">Ver ficha completa <ChevronRight size={16}/></div>
  </motion.button>;
}
function DetailModal({ selected, onClose }) {
  return <AnimatePresence>{selected && <motion.div className="modalBackdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}><motion.article className="modal" initial={{scale:.94,y:20,opacity:0}} animate={{scale:1,y:0,opacity:1}} exit={{scale:.94,y:20,opacity:0}} onClick={e=>e.stopPropagation()} style={{'--c':selected.color}}><button className="close" onClick={onClose}><X size={20}/></button><div className="modalHead"><BotanicalArt family={selected.family} icon={selected.icon} color={selected.color}/><div><p className="modalOrder">Orden {selected.order}</p><h2>{selected.family}</h2><p>{selected.note}</p></div></div><div className="modalGrid"><section><h4>Características</h4>{selected.traits.map(x => <p key={x}>• {x}</p>)}</section><section><h4>Usos</h4><div className="chips big">{selected.uses.map(x => <span key={x}>{x}</span>)}</div></section><section className="wide"><h4>Representantes</h4><div className="repGrid">{selected.reps.map(x => <div key={x} className="rep">{selected.icon} {x}</div>)}</div></section></div></motion.article></motion.div>}</AnimatePresence>;
}
export default function App(){
  const [active,setActive]=useState(laminas[0].id),[query,setQuery]=useState(''),[order,setOrder]=useState('Todos'),[selected,setSelected]=useState(null),[presentation,setPresentation]=useState(false);
  const lamina=laminas.find(l=>l.id===active);
  const orders=useMemo(()=>['Todos',...Array.from(new Set(lamina.families.map(f=>f.order))).sort()],[lamina]);
  const filtered=lamina.families.filter(f=>`${f.family} ${f.order} ${f.reps.join(' ')} ${f.uses.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (order==='Todos'||f.order===order));
  return <main className={presentation?'presentation app':'app'}><section className="hero"><div className="heroBg"/><div className="badge"><Sparkles size={16}/> APG IV · Angiospermas</div><h1>Esquema Taxonómico de Angiospermas Representativas</h1><p className="heroText">Infografía web interactiva para exposición: explora familias, órdenes, características, usos y especies representativas de los tres documentos.</p><div className="heroActions"><button onClick={()=>setPresentation(!presentation)}><Presentation size={18}/>{presentation?'Salir de presentación':'Modo presentación'}</button><a href="#laminas"><BookOpen size={18}/> Ver láminas</a></div></section><section id="laminas" className="workspace"><div className="tabs">{laminas.map(l=><button key={l.id} onClick={()=>{setActive(l.id);setOrder('Todos');setQuery('')}} className={active===l.id?'active':''} style={{'--c':l.accent}}><span>{l.title}</span><small>{l.families.length} familias</small></button>)}</div><div className="panelHead"><div><p className="source"><Sprout size={16}/> {lamina.source}</p><h2>{lamina.title}: familias representativas</h2><p>{lamina.description}</p></div><div className="centerOrb" style={{'--c':lamina.accent}}><span>APG IV</span><strong>{lamina.families.length}</strong><small>familias</small></div></div><div className="tools"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar familia, orden, uso o especie..."/></label><label><Filter size={18}/><select value={order} onChange={e=>setOrder(e.target.value)}>{orders.map(o=><option key={o}>{o}</option>)}</select></label></div><div className="taxonomyMap"><div className="hub" style={{'--c':lamina.accent}}><Leaf/><b>APG IV</b><span>{lamina.title}</span></div><div className="cardsGrid">{filtered.map((item,i)=><FamilyCard key={item.family} item={item} index={i} onOpen={setSelected}/>)}</div></div></section><footer>Diseño interactivo para presentación académica · Familias de angiospermas APG IV</footer><DetailModal selected={selected} onClose={()=>setSelected(null)}/></main>;
}
